package com.HungryBells.DTO;

public enum ServiceListenerType {
    LOC_FIND, TRANSACTIONQUERY, FAV_RESTARUNT, TERMS_CONDITIONS, FEEDBACK_ADS, NOTIFI_PREF, COUSINE_PREF, NOTIFI_PREF_EDIT, AD_SETTINGS, USERPROFILE, CUSTOMER_ADD, CUSTOMER_EDIT, CUSTOMER_LOGIN, GET_ALLDEALS, LIKE_COUPONS, LIKE_ADS, FAV_REST, SUBMITDATA, NOTIFI_PREF_DETAILS, FEEDBACK_INSERT, NOTIFIC_SENDDATA, GET_LOCATION, GET_FOODCATEGORY, NOTIFI_PREF_PROFILE_DETAILS, NOTIFI_PREF_SIGNUP_DETAILS, NOTIFI_PREF_SETTINGS, MY_ORDERS, ERROR_MSG, ERRORMSG;
}
